# Generated by Django 5.0.1 on 2026-02-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cloudinary_resource_type',
            field=models.CharField(default='raw', max_length=20),
        ),
    ]
